name: CI - Build e Teste

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar projeto
        run: |
          mkdir -p build
          javac -d build $(find . -name "*.java")

      - name: Verificar se compilou arquivos
        run: |
          if [ -z "$(find build -name '*.class')" ]; then
            echo "Nenhuma classe gerada!"
            exit 1
          else
            echo "Compilação OK"
          fi